### ISSUE TITLE
UUID for provider is 0 (zero)

### ISSUE THREAD

**Issue by mihow** [flipboxfactory/saml-sp#49]
I have a fresh install of the SAML Service Provider plugin v2.0.15 running on Craft Pro 3.3.18.1. When I add an Identity Provider (I've tried Okta & GSuite) the UUID of the provider is saved as `0` and does not let me log in. If I add multiple providers, both UUIDs are the same (`0`). 

![image](https://user-images.githubusercontent.com/158175/71941766-c84f6a00-316f-11ea-801e-d0b8c9498715.png)

![image](https://user-images.githubusercontent.com/158175/71941834-05b3f780-3170-11ea-92b4-7a68cc6e6dd0.png)

There is actually whitespace saved as part of the UUID as you can see in the URL in the screenshots above.

`/sso/login/request/0                                   `

I've followed the blog post explaining how to integrate with Okta (which was very helpful thank you) however am still running into this issue.
https://www.flipboxdigital.com/insights/configuring-saml-sp-with-okta-com

I've tried uninstalling and reinstalling the plugin to no avail.

**Comment by dsmrt** [comment]
Couple questions:

What DB (mysql/psql) are you using?
If you look in the db, there should be a table named: `saml_sp_providers`. Can you see the uids in there?

**Comment by mihow** [comment]
We are using Postgres 10. I see the `saml_sp_providers` table and there are entries for the service provider and the identity providers. The uid is `0                                   ...` for all of them (zero followed by 35 chars of whitespace).

![image](https://user-images.githubusercontent.com/158175/71959338-5d218a00-31a7-11ea-948c-283efbca3238.png)

**Comment by dsmrt** [comment]
Ok. That should not look like that. I’ll try and replicate with pg 10.

**Comment by mihow** [comment]
Thanks for looking into this. I also tried manually changing the UID in the database but I am still seeing the same issues when initiating the login:

![image](https://user-images.githubusercontent.com/158175/72004108-9259c680-31ff-11ea-92a9-72371c676f50.png)

![image](https://user-images.githubusercontent.com/158175/72004085-8837c800-31ff-11ea-8b04-03ed3303e0cc.png)

**Comment by dsmrt** [comment]
Not sure what is going wrong here but the uid is taking the default which is `0` in postgres (see `\craft\db\Migration::uid`). Trying to figure out why that isn't being set correctly for PG. You 404 is happening with the zero and the 111... due to the url route rule that requires a uuid format 
(`<uid:[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}>`, from `vendor/flipboxfactory/saml-core/src/AbstractPlugin.php:297`)

**Comment by dsmrt** [comment]
@mihow , I've pushed up patch in 2.1.1. Run a `composer update flipboxfactory/saml-sp flipboxfactory/saml-core`. The patch is in core but update both. Let me know if that works out for you. Thanks!

**Comment by mihow** [comment]
That worked! I have real UUIDs now! Thank you.

I am getting a 400 error now but guessing it's related to my configuration "Service Provider is not found. Possibly a configuration problem. My Provider/Current EntityId: /"

**Comment by dsmrt** [comment]
Have you created the My Provider yet? if you goto the provider listing, you should have 2 providers there. One defining your craft site, and the other, defining the IdP. You can click the "My Provider" nav item in the SAML plugin sub nav to verify it's been created. If not, just create it then. 

Let me know if this doesn't line up with what you are seeing.

**Comment by mihow** [comment]
Hi @dsmrt, I have a My Provider created but am still seeing this issue. Any other ideas? I tried starting from scratch but no luck.

![image](https://user-images.githubusercontent.com/158175/72299473-cf65f480-3615-11ea-8647-8232ed4a491b.png)

![image](https://user-images.githubusercontent.com/158175/72299482-d5f46c00-3615-11ea-9b04-267b8da3235b.png)

Another issue is the Single Logout Service URL is missing under Bindings for My Provider. 

![image](https://user-images.githubusercontent.com/158175/72299585-1d7af800-3616-11ea-89f9-64d7861f984c.png)

**Comment by dsmrt** [comment]
In your `config/general.php` can you configure your `loginPath` to point to `/sso/login/request`? See if that helps.

**Comment by mihow** [comment]
Unfortunately no dice. This is the URL that the "login via Okta" button takes me too, which has the correct UID of the identity provider.
 
http://localhost:9000/sso/login/request/ed17832a-0c8d-4cce-a897-fc571a431d43?RelayState=http://localhost:9000/admin

**Comment by dsmrt** [comment]
Ok ... judging from the screenshot, your EntityId has been changed to `/` system wide somewhere. 
Your EntityId needs to match `http://localhost:9000`. The plugin defaults EntityId to the siteUrl. 

Check your:
- `project.yaml`
   - if you are using the project config delete the entityId entry. See https://github.com/flipboxfactory/saml-sp/issues/29#issuecomment-522168846 for more info.
- `config/saml-sp.php`
   - if you are overwriting the entityId here, remove that.
- Plugin Settings (`/admin/saml-sp/settings`)
   - Delete the entityId text and hit save. Go back and make sure it's back to the default.

**Comment by mihow** [comment]
That worked! We are using project.yaml and the setting must have stuck even after reinstalling the plugin. Thank you for your help.
